version: '3.9'
services:
  postgres:
    image: postgres:14.3-alpine
    container_name: postgres
    restart: always
    env_file: .env
    ports:
      - 5432:5432
  web:
    build: .
    container_name: web
    depends_on:
      - postgres
    ports:
      - 3001:3001
    env_file: .env
    working_dir: /app
    command: npm run start:dev
    volumes:
      - .:/app